spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/data/quiz-database.db
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true  # Enable SQL logging
    properties:
      hibernate:
        format_sql: true  # Enable SQL formatting for log readability

